### ISSUE TITLE
Leading zeros

### ISSUE THREAD

**Issue by therustmonk** [ggb/numeral-elm#10]
It's cool to have possibility to add leading zeros:
`12 > '000' > 012`
This feature is helpful for formatting to strict width or to format something like bill numbers.
Does this feature exists and works it another way? I haven't found any example.

**Comment by ggb** [comment]
I'm not sure if this is possible in one or another way at the moment. I'll have a look into it...

**Comment by ggb** [comment]
Hi Denis,

sorry for the delay, too many other things to do... I've just pushed a working solution to master. Could you please provide some more test cases or some more examples in general so that I can check if this solution works as expected? Thanks!

**Comment by ggb** [comment]
I've added test cases on my own, the feature is available with 1.3.0 (already on elm-package).
