### ISSUE TITLE
Package not installable with 0.18

### ISSUE THREAD

**Issue by mkaulig** [ggb/numeral-elm#11]
I tried to install the newest package (1.2.3) with elm version 0.18 but I get the following error:

```
elm package install ggb/numeral-elm 1.2.3
Error: I cannot find a set of packages that works with your constraints.

--> There are no versions of circuithub/elm-number-format that work with Elm
    0.18.0. Maybe the maintainer has not updated it yet.
```
Maybe you have to release it with the major version number incremented?

**Comment by ggb** [comment]
Hm, I just tried it and it works fine (and we even used it in production with 0.18 for a few weeks). Do you know why circuithub/elm-number-format appears in the error message?

**Comment by mkaulig** [comment]
Thank you for the fast response. You are right, my elm-package.json had a reference to a non 0.18 package which lead to the error. Sorry for the inconvenience.
