### ISSUE TITLE
Upgrade to Elm 0.19

### ISSUE THREAD

**Issue by wmakley** [ggb/numeral-elm#15]
I rely on this library, so I'm working on an upgrade on a fork. (Please let me know if redundant.) I'm keeping the style intact (and not elm-formatting it), just making the minimally necessary changes. The biggest issue is the Regex package API changed a lot. Everything else was a minor change.

**Comment by ggb** [comment]
I've just pushed the changes for 0.19. At the moment I'm not able to update the library on elm-package, because of issues with elm-test. As soon as I've solved these issues, I'll publish the new version.

Thanks for your work!

**Comment by wmakley** [comment]
Awesome, thanks! Really appreciate this library.

**Comment by ggb** [comment]
I was finally able to run the tests and fix issues, that (of course) popped up. But now everything is fine again and the new version is published to elm-package. Please let me know, if you run into any issues.
