### ISSUE TITLE
Thousands separator in German locale wrong

### ISSUE THREAD

**Issue by peteralbert** [ggb/numeral-elm#16]
Hi,

thanks for the great package!

We noticed that the German locale contains some errors. The thousands separator is `.` (dot), not ` ` (space).

Also, one could argue that the abbreviations are not correct. While the abbreviations configured are used when it comes to SI based units (e.g. ´kg´ for thousand gram), the German abbreviations for currencies and other units are `Tsd.` for thousands, `Mil.` for million, `Mrd.`  for billion and `Bil.` for trillion.

So the full config would look like this:

```
lang =
  { delimiters=
    { thousands="."
    , decimal=","
    }
  , abbreviations=
    { thousand="Tsd."
    , million="Mil."
    , billion="Mrd."
    , trillion="Bil."
    }
  , ordinal=germanOrdinal
  , currency=
    { symbol="€"
    }
  }
```

Happy to provide a PR if this helps.

Thanks, Peter

**Comment by ggb** [comment]
Hallo Peter,

wunderlich, dass mir das nie aufgefallen ist, so als Muttersprachler... Ich hab' es angepasst und die neue Version ist bereits auf package.elm-lang.org

Danke für den Hinweis
Gregor
