### ISSUE TITLE
Move Language module to Numeral.Language to avoid import conflicts

### ISSUE THREAD

**Issue by slissner** [ggb/numeral-elm#17]
It would be great to consider moving the `Language` module to `Numeral.Language`. This could avoid naming conflicts within the existing codebase, e.g. shocking with existing `Language` module.

**Comment by ggb** [comment]
Hi,

and sorry for my late response. I've long thought about your proposal, but I don't really get the benefit/see the problem. Could you elaborate on how this is an issue? May be with an example?

Thanks :)
