### ISSUE TITLE
Custom unit suffix

### ISSUE THREAD

**Issue by therustmonk** [ggb/numeral-elm#9]
It's good to have custom unit prefix/suffix like:
**12345** -> **"0,0[ pcs.]"** -> **"12,345 pcs."**

**Comment by ggb** [comment]
Hi, sounds like a reasonable and good idea. I'll have a look into it. Thanks for your suggestion!

**Comment by therustmonk** [comment]
Thank you! I am at your service and ready to write some code if you need it.

**Comment by ggb** [comment]
I've implemented this enhancement and published version 1.2.2 to elm package. Please note that it's not possible to use numbers as unit suffix at the moment.

**Comment by therustmonk** [comment]
Thank you a lot! It works fine! :tada:
